name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    env:
      ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY}}
      API_KEY: ${{secrets.API_KEY}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      WALLET_PRIVATE_KEY: ${{secrets.WALLET_PRIVATE_KEY}}
      REDIS_URI: ${{secrets.REDIS_URI}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Fix Git Safe Directory Issue
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Clean up Git Submodule Configurations
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --local --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive git config --local --unset-all core.sshCommand || true

      - name: Install Dependencies
        run: |
          npm install

      - run: npm run build
      - name: Set Secrets and Change Dir
        run: | # Secrets needed on the server
          echo "ALCHEMY_API_KEY=${{secrets.ALCHEMY_API_KEY}}" >> .env
          echo "API_KEY=${{secrets.API_KEY}}" >> .env
          echo "MONGODB_URI=${{secrets.MONGODB_URI}}" >> .env
          echo "WALLET_PRIVATE_KEY=${{secrets.WALLET_PRIVATE_KEY}}" >> .env
          echo "REDIS_URI=${{secrets.REDIS_URI}}" >> .env

      - name: Validate .env contents
        run: cat .env

      # - name: change directory
      # run: cd /home/leo/runners/nfttools-websocket/_work/nfttools-websocket/nfttools-websocket
      # - run: pm2 restart nfttools-websocket
